steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'
    displayName: 'Install Node.js'
  - script: 'npm install --global yarn'
    displayName: 'Install Yarn'
  - script: |
      cd website-react-spa && yarn install
    retryCountOnTaskFailure: 3
    displayName: 'Initialize project'
  - task: DownloadSecureFile@1
    displayName: 'Download Env variables for production'
    inputs:
      secureFile: '.env.production'
  - task: CopyFiles@2
    displayName: 'Copy .env vars file to project root'
    inputs:
      sourceFolder: '$(Agent.TempDirectory)'
      contents: '**/*.env.production'
      targetFolder: 'website-react-spa/'
      cleanTargetFolder: false
  - script: |
      cd website-react-spa && yarn build
    displayName: 'Build the project'
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'website-react-spa/build'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      cleanTargetFolder: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      includeRootFolder: false
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
