steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'
    displayName: 'Install Node.js'
  - script: 'npm install --global yarn'
    displayName: 'Install Yarn'
  - script: |
      cd website-vue-spa && yarn install
    displayName: 'Initialize project'
  - script: |
      cd website-vue-spa && yarn build-only
    displayName: 'Build the project'
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'website-vue-spa/dist'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      cleanTargetFolder: true
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      includeRootFolder: false
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
