steps:
  - download: current
    artifact: drop
  - task: AzureWebApp@1
    displayName: 'Deploy react front-end webapp to azure app service'
    inputs:
      azureSubscription: '$(managedIdentityName)'
      appName: '$(project)-$(environment)-$(webAppName)'
      appType: 'webAppLinux'
      package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
      appSettings: |
        -APPINSIGHTS_INSTRUMENTATIONKEY $(keyVaultAppInsightsKey) 
        -APPLICATIONINSIGHTS_CONNECTION_STRING $(keyVaultAppInsightsConnectionString) 
        -APPINSIGHTS_PROFILERFEATURE_VERSION 1.0.0 
        -APPINSIGHTS_SNAPSHOTFEATURE_VERSION 1.0.0 
        -ApplicationInsightsAgent_EXTENSION_VERSION ~3 
        -DiagnosticServices_EXTENSION_VERSION ~3 
        -InstrumentationEngine_EXTENSION_VERSION disabled 
        -SnapshotDebugger_EXTENSION_VERSION disabled 
        -XDT_MicrosoftApplicationInsights_BaseExtensions disabled 
        -XDT_MicrosoftApplicationInsights_Mode recommended 
        -XDT_MicrosoftApplicationInsights_PreemptSdk disabled
