#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN="\033[0;32m"
NC="\033[0m"

# format backend backend dotnet
echo -e "${GREEN}formatting dotnet code${NC}"
dotnet format integrations-dotnet-api/integrations-dotnet-api.sln --verbosity detailed

# format frontend js code
echo -e "${GREEN}formatting js code${NC}"
cd website-react-spa
yarn lint-staged


# autogenerate terraform readme.md docs
echo -e "${GREEN}auto-generating terraform readme.md${NC}"
cd ../terraform-infra/terraform/
terraform-docs -c .\tfdocs-config.yml .
cd ../..
