trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - website-react-spa/*
      - integrations-dotnet-api/*
      - website-angular-spa/*
      - website-vue-spa/*

parameters:
  - name: forceApiRecreation
  - type: boolean
  - default: false
  - displayName: "Force APIM API re-creation?"
  - description: "Set to true to delete the APIM API to that terraform can re-create it." 


variables:
  - template: 'variables/service-connections.yml'
  - template: 'variables/build.yml'

pool:
  vmImage: '$(buildVmImage)'

stages:
  - stage: 'Build'
    displayName: 'Build Terraform IAC'
    jobs:
      - job: 'Build'
        displayName: 'Build job'
        steps:
          - template: './steps/build.yml'

  - stage: 'Dev_Validate_Plan'
    displayName: 'Validate Terraform Plan on Dev Env'
    dependsOn: 'Build'
    condition: and (succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    variables:
    - template: 'variables/dev.yml'
    jobs:
      - deployment: 'Validate'
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: './steps/deploy.yml'
                  parameters:
                    applyChanges: false

  - stage: 'Dev_Deploy'
    displayName: 'Deploy to Dev Environment'
    dependsOn: 'Build'
    condition: and (succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    variables:
    - template: 'variables/dev.yml'
    jobs:
      - deployment: 'Deploy'
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: './steps/deploy.yml'
                  parameters:
                    applyChanges: true
                    forceApiRecreation: ${{ parameters.forceApiRecreation }}
