steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 9.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions

  - task: DotNetCoreCLI@2
    displayName: Restore WebApi
    inputs:
      command: 'restore'
      projects: '**/WebApi.csproj'
      includeNuGetOrg: true

  - task: DotNetCoreCLI@2
    displayName: 'Verify no formatting errors'
    continueOnError: true
    inputs:
      command: 'custom'
      custom: 'format'
      arguments: 'integrations-dotnet-api/integrations-dotnet-api.sln --verify-no-changes --verbosity detailed'

  - task: DotNetCoreCLI@2
    displayName: Build WebApi
    inputs:
      command: build
      projects: '**/WebApi.csproj'
      arguments: '--no-restore --configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Publish WebApi
    inputs:
      command: publish
      projects: '**/WebApi.csproj'
      publishWebProjects: false
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Dotnet Release to  drop'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Swagger json to drop'
    inputs:
      pathtoPublish: 'integrations-dotnet-api/src/WebApi/swagger.json'
