steps:
  - download: current
    artifact: drop

  - task: AzureFileCopy@4
    displayName: Copy swagger json definition to az storage
    inputs:
      sourcePath: '$(Pipeline.Workspace)/drop/swagger.json'
      azureSubscription: '$(managedIdentityName)'
      destination: AzureBlob
      storage: $(adminStorageAccount)
      containerName: $(swaggerContainer)
      cleanTargetBeforeCopy: true

  - task: AzureWebApp@1
    displayName: 'Deploy .net core api to azure app service'
    inputs:
      azureSubscription: '$(managedIdentityName)'
      appName: '$(project)-$(environment)-$(webAppName)'
      appType: 'webAppLinux'
      package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
      appSettings: |
        -APPINSIGHTS_INSTRUMENTATIONKEY $(keyVaultAppInsightsKey) 
        -APPLICATIONINSIGHTS_CONNECTION_STRING $(keyVaultAppInsightsConnectionString) 
        -APPINSIGHTS_PROFILERFEATURE_VERSION 1.0.0 
        -APPINSIGHTS_SNAPSHOTFEATURE_VERSION 1.0.0 
        -ApplicationInsightsAgent_EXTENSION_VERSION ~3 
        -DiagnosticServices_EXTENSION_VERSION ~3 
        -InstrumentationEngine_EXTENSION_VERSION ~1 
        -SnapshotDebugger_EXTENSION_VERSION ~1 
        -XDT_MicrosoftApplicationInsights_BaseExtensions ~1 
        -XDT_MicrosoftApplicationInsights_Mode recommended 
        -XDT_MicrosoftApplicationInsights_PreemptSdk disabled 
        -IntegrationOptions__LogicAppSendEmailUrl $(keyVaultLogicAppSendEmailUrlKey) 
        -IntegrationOptions__LogicAppDomain $(logicAppDomainUrl) 
        -Persistence__SqlServerConnectionString $(azureSqlServerConnectionString) 
